In [61]:
###########################################################################################
# Google searches from data range '2020-01-01 to 2020-04-26' by the following key words

# Intrests analyzed by date

#'domestic flight','travel','vacation','resorts','hotels','travel visa','airline ticket',
#'best hotels','airbnb','park'

#For USA region and the category is Travel(67)

###########################################################################################


import pandas as pd                        
from pytrends.request import TrendReq
pytrend = TrendReq()

pytrend = TrendReq(hl='en-US',geo = 'US', tz=360)

start_dt = '2020-01-01'

end_dt = '2020-04-26'

keywords = ['domestic flight','travel','vacation','resorts','hotels',
            'travel visa','airline ticket','best hotels','airbnb','park']
key = []
for i in keywords:
    key.append([i])
key

for i in range(0,len(key)):
    pytrend.build_payload(
        kw_list=key[i],
        cat=67,
        timeframe= start_dt + ' ' + end_dt ,
        geo='US',
        gprop='')
    data = pytrend.interest_over_time()
    data = data.drop(labels=['isPartial'],axis='columns')
    if i == 0:
        data1 = data
    else:
        data1 = pd.merge(data1, data, on='date')

data1 = data1[sorted([col for col in data1.columns])]
data1
#data1.to_csv(r'C:\Users\Anil\OneDrive\Desktop\AnujAdhoc\google-topics-by-date1.csv')

,airbnb,airline ticket,best hotels,domestic flight,hotels,park,resorts,travel,travel visa,vacation
date,,,,,,,,,,
2020-01-01,64,30,61,2,66,92,84,18,27,89
2020-01-02,87,39,78,11,77,83,88,23,47,100
2020-01-03,86,38,86,6,77,80,90,25,46,91
2020-01-04,84,55,70,6,74,87,83,22,100,100
2020-01-05,80,69,86,9,76,79,100,21,75,99
...,...,...,...,...,...,...,...,...,...,...
2020-04-19,22,30,19,2,34,55,29,12,22,36
2020-04-20,25,5,16,2,27,45,24,12,19,33
2020-04-21,22,10,20,2,27,42,25,12,37,29
2020-04-22,23,26,13,2,27,45,26,11,19,30
2020-04-23,25,31,21,4,29,43,24,13,28,33

In [62]:
###########################################################################################
# Google searches from data range '2020-01-01 to 2020-04-26' by the following key words

#Intrests analyzed by region

#'domestic flight','travel','vacation','resorts','hotels','travel visa','airline ticket',
#'best hotels','airbnb','park'

#For USA region and the category is Travel(67)

###########################################################################################

import pandas as pd                        
from pytrends.request import TrendReq
pytrend = TrendReq()

start_dt = '2020-01-01'

end_dt = '2020-04-26'

pytrend = TrendReq(hl='en-US',geo = 'US', tz=360)

keywords = ['domestic flight','travel','vacation','resorts','hotels',
            'travel visa','airline ticket','best hotels','airbnb','park']
key = []
for i in keywords:
    key.append([i])
    
for i in range(0,len(key)):
    pytrend.build_payload(
        kw_list=key[i],
        cat=67,
        timeframe=start_dt + ' ' + end_dt,
        geo='US',
        gprop='')
    data = pytrend.interest_by_region()
    if i == 0:
        data1 = data
    else:
        data1 = pd.merge(data1, data, on='geoName')

data1  = data1[sorted([col for col in data1.columns])]
data1['date'] = end_dt
#data1.to_csv(r'C:\Users\Anil\OneDrive\Desktop\AnujAdhoc\google-topics-by-region1.csv')

In [63]:
data1

,airbnb,airline ticket,best hotels,domestic flight,hotels,park,resorts,travel,travel visa,vacation,date
geoName,,,,,,,,,,,
Alabama,28,20,41,20,72,27,64,37,16,65,2020-04-26
Alaska,57,100,36,46,40,19,26,67,100,47,2020-04-26
Arizona,40,46,50,26,66,30,53,51,8,47,2020-04-26
Arkansas,27,34,44,10,61,24,61,33,15,67,2020-04-26
California,53,45,62,39,54,33,39,51,27,45,2020-04-26
Colorado,50,36,53,48,52,40,68,59,17,55,2020-04-26
Connecticut,39,27,61,27,60,25,81,50,44,83,2020-04-26
Delaware,43,58,53,27,67,26,93,45,78,85,2020-04-26
District of Columbia,71,63,100,33,68,33,77,87,47,61,2020-04-26
Florida,45,45,62,36,81,35,71,53,23,65,2020-04-26
Georgia,38,39,49,28,72,26,75,44,11,67,2020-04-26
Hawaii,100,76,49,100,57,48,56,100,55,71,2020-04-26
Idaho,43,41,45,24,48,27,46,44,48,54,2020-04-26
Illinois,36,40,49,29,54,35,75,49,19,70,2020-04-26
Indiana,32,26,43,18,57,28,74,47,24,80,2020-04-26
Iowa,30,36,39,25,48,26,71,44,13,70,2020-04-26
Kansas,28,32,39,15,49,27,61,38,14,63,2020-04-26
Kentucky,27,31,50,21,66,26,65,33,18,81,2020-04-26
Louisiana,25,31,39,23,71,23,63,35,9,74,2020-04-26
Maine,46,51,54,20,51,26,72,48,0,90,2020-04-26
Maryland,39,43,47,29,60,26,80,49,10,68,2020-04-26
Massachusetts,48,31,70,35,52,25,77,56,20,92,2020-04-26
Michigan,35,36,47,29,56,24,73,44,17,71,2020-04-26
Minnesota,42,52,42,36,44,32,91,53,21,69,2020-04-26
Mississippi,20,30,47,18,92,20,68,34,17,70,2020-04-26
Missouri,33,35,42,20,50,30,67,38,12,73,2020-04-26
Montana,42,52,43,14,50,39,52,51,0,59,2020-04-26
Nebraska,32,32,37,16,47,28,72,41,18,64,2020-04-26
Nevada,63,50,62,40,73,39,93,53,35,67,2020-04-26
New Hampshire,48,13,65,18,54,24,77,46,0,100,2020-04-26
New Jersey,35,43,62,37,52,29,78,52,22,73,2020-04-26
New Mexico,36,34,55,20,67,24,42,41,0,54,2020-04-26
New York,41,45,91,36,100,32,100,60,25,92,2020-04-26
North Carolina,39,27,45,20,67,26,74,40,13,65,2020-04-26
North Dakota,32,40,54,18,65,24,80,57,0,62,2020-04-26
Ohio,33,30,45,21,58,27,71,39,10,80,2020-04-26
Oklahoma,29,25,39,6,50,23,56,37,0,63,2020-04-26
Oregon,46,40,54,26,46,31,40,56,21,49,2020-04-26
Pennsylvania,35,38,52,24,56,27,78,43,11,78,2020-04-26
Rhode Island,42,30,55,10,57,21,72,48,30,85,2020-04-26
South Carolina,44,39,53,12,85,26,83,41,23,81,2020-04-26
South Dakota,26,38,22,35,52,23,61,82,0,67,2020-04-26
Tennessee,36,23,47,30,67,29,70,37,11,76,2020-04-26
Texas,33,28,48,20,53,28,56,40,12,57,2020-04-26
Utah,58,28,61,21,56,100,54,51,44,53,2020-04-26
Vermont,63,76,52,41,45,28,66,50,61,63,2020-04-26
Virginia,37,43,49,23,56,24,71,49,19,63,2020-04-26
Washington,49,43,50,44,43,29,46,59,34,52,2020-04-26
West Virginia,22,20,36,9,62,21,60,29,0,82,2020-04-26
Wisconsin,36,33,42,14,49,29,68,52,9,75,2020-04-26
Wyoming,37,39,60,54,66,38,60,50,0,78,2020-04-26

In [ ]:
import pymysql
connection = pymysql.connect(host='127.0.0.1',
                             user='anil',
                             password='anil',
                             db='testpd')

In [24]:
data2 = data1.reset_index()
date = data2['date']
date

0     2020-01-01
1     2020-01-02
2     2020-01-03
3     2020-01-04
4     2020-01-05
         ...
109   2020-04-19
110   2020-04-20
111   2020-04-21
112   2020-04-22
113   2020-04-23
Name: date, Length: 114, dtype: datetime64[ns]

In [25]:
airbnb = data2['airbnb']
airline_ticket = data2['airline ticket']
airline_ticket

0      30
1      39
2      38
3      55
4      69
       ..
109    30
110     5
111    10
112    26
113    31
Name: airline ticket, Length: 114, dtype: int32

In [77]:
#########################################################################################
#To connect to data base we need to initlialise local host port for listening
#
#
#cloud_sql_proxy -instances= <instance name> -credential_file=<json file> &
#json file = C:\Users\Anil\OneDrive\Desktop\AnujAdhoc\abc.json
#cloudapi-260317:us-central1:pandamic-database=tcp:3306
#
#
#
#reference : https://github.com/GoogleCloudPlatform/python-docs-samples/blob/master/cloud-sql/mysql/sqlalchemy/main.py
#


#########################################################################################

In [78]:
import sqlalchemy

db = sqlalchemy.create_engine('mysql+pymysql://anil:anil@127.0.0.1:3306/testpd')

In [76]:
a = "'2020-08-19'"
b = "'84'"
s1 = 'INSERT INTO gdata (date, airbnb) VALUES ('
s2 = ')'
k = s1 + a +',' + b + s2
print(k)

s = "INSERT INTO gdata (date, airbnb)" " VALUES ('2020-04-28', '98')"
print(s)
stmt = sqlalchemy.text(k)
    # Using a with statement ensures that the connection is always released
    # back into the pool at the end of statement (even if an error occurs)
# stmt = sqlalchemy.text(
#         "INSERT INTO gdata (date, airbnb)" " VALUES ('2020-04-26', '58')"
#     )
with db.connect() as conn:
    conn.execute(stmt)
print(stmt)

INSERT INTO gdata (date, airbnb) VALUES ('2020-08-19','84')
INSERT INTO gdata (date, airbnb) VALUES ('2020-04-28', '98')
INSERT INTO gdata (date, airbnb) VALUES ('2020-08-19','84')

In [65]:
with db.connect() as conn:
#         conn.execute(
#             "CREATE TABLE IF NOT EXISTS gtd3 "
#             "(date  char,airbnb int,airline_ticket int,best_hotels int,domestic_flight int,"
#             "hotels int,park int,resorts int,travel int,travel_visa int,vacation int);"
#         )
        conn.execute(
            "CREATE TABLE IF NOT EXISTS gdata"
            "(date  char(20),airbnb int);"
        )
#         a = conn.execute("select date from gtd")
#         a = a.fetchall()

In [15]:
import pandas as pd
a = pd.DataFrame(a)
a

              0
0    0000-00-00
1    0000-00-00
2    0000-00-00
3    0000-00-00
4    0000-00-00
..          ...
110  0000-00-00
111  0000-00-00
112  0000-00-00
113  0000-00-00
114  0000-00-00

[115 rows x 1 columns]